# This script performs the differential expression analysis for the RNA-seq data.
# It uses the gene-level expression estimates generated by RSEM and compares each
# knockout genotype with the wild-type control.
#
# tximport reads the RSEM output and prepares the count and gene-length information
# for DESeq2. DESeq2 then normalizes the read counts to account for differences in
# sequencing depth between samples and models gene expression according to genotype.
#
# Genes with very low read counts are removed before statistical testing because
# they contain little information and can add noise to the analysis. The fitted
# DESeq2 model is then used to calculate differential expression for every HP1
# knockout and for the H3K9 methyltransferase quadruple knockout compared with WT.
#
# The script also saves normalized count matrices and variance-stabilized expression
# values that are used later for PCA, heatmaps and other RNA-seq plots.


# -----------------------
# Install packages if missing
# -----------------------

# Checks whether BiocManager is available.
# Bioconductor provides R packages and reference data for bioinformatics and
# biological data analysis, and BiocManager is used to install these packages.
if (!requireNamespace("BiocManager", quietly = TRUE)) {

  install.packages(
    "BiocManager",
    repos = "https://cloud.r-project.org"
  )
}


# Checks whether DESeq2 is available and installs it from Bioconductor if needed.
# DESeq2 performs normalization and statistical testing of RNA-seq count data.
if (!requireNamespace("DESeq2", quietly = TRUE)) {

  BiocManager::install(
    "DESeq2",
    ask = FALSE
  )
}


# Checks whether tximport is available and installs it from Bioconductor if needed.
# tximport reads the RSEM quantification results and prepares them for DESeq2.
if (!requireNamespace("tximport", quietly = TRUE)) {

  BiocManager::install(
    "tximport",
    ask = FALSE
  )
}


# -----------------------
# Load libraries
# -----------------------

# DESeq2 is used for count normalization and differential expression analysis.
library(DESeq2)

# tximport is used to import the gene-level RSEM quantification results.
library(tximport)


# -----------------------
# Settings
# -----------------------

# Defines the main RNA-seq project folder.
project_dir <- "/home1/RNAseq"


# Folder containing the gene-level expression results generated by RSEM.
rsem_dir <- file.path(
  project_dir,
  "03_RSEM_results"
)


# Folder where the DESeq2 results and expression matrices are saved.
out_dir <- file.path(
  project_dir,
  "04_DESeq2_results"
)


# Creates the output folder if it does not already exist.
dir.create(
  out_dir,
  showWarnings = FALSE,
  recursive = TRUE
)


# -----------------------
# Find RSEM gene result files
# -----------------------

# Finds all RSEM gene-level result files in the RSEM output folder.
files <- list.files(
  path = rsem_dir,
  pattern = "\\.genes\\.results$",
  full.names = TRUE
)


# Stops the script if no RSEM gene result files were found.
if (length(files) == 0) {

  stop(
    "No .genes.results files found in: ",
    rsem_dir
  )
}


# Extracts the sample names by removing the .genes.results suffix from each filename.
sample_names <- sub(
  "\\.genes\\.results$",
  "",
  basename(files)
)


# Assigns the sample names to the file paths so tximport can keep track
# of which RSEM result belongs to which sample.
names(files) <- sample_names


# Prints the detected RSEM files and their assigned sample names.
print(files)


# -----------------------
# Define genotype groups from sample names
# -----------------------

# Expected sample name examples:
# TT2-NT_rep1, A6-OHT_rep1, 3S1G-OHT_rep1, A21_rep1,
# B23_rep1, G2_rep1, BA3_rep1, GA6_rep1, GB18_rep1
#
# Genotype interpretation:
# TT2-NT   = wild-type control
# A21      = HP1alpha single KO
# B23      = HP1beta single KO
# G2       = HP1gamma single KO
# BA3      = HP1alpha/beta double KO
# GA6      = HP1alpha/gamma double KO
# GB18     = HP1beta/gamma double KO
# A6-OHT   = HP1alpha/beta/gamma triple KO
# 3S1G-OHT = H3K9 methyltransferase quadruple KO


# Assigns each sample to its biological genotype based on the beginning of
# the sample name. This information is later used by DESeq2 to compare
# each knockout group with WT.
get_genotype <- function(sample) {

  if (grepl("^TT2-NT|^TT2_NT|^TT2", sample)) {

    return("WT")

  } else if (grepl("^A21", sample)) {

    return("HP1a_KO")

  } else if (grepl("^B23", sample)) {

    return("HP1b_KO")

  } else if (grepl("^G2", sample)) {

    return("HP1g_KO")

  } else if (grepl("^BA3", sample)) {

    return("HP1ab_DKO")

  } else if (grepl("^GA6", sample)) {

    return("HP1ag_DKO")

  } else if (grepl("^GB18", sample)) {

    return("HP1bg_DKO")

  } else if (grepl("^A6-OHT|^A6_OHT|^A6", sample)) {

    return("HP1abg_TKO")

  } else if (grepl("^3S1G-OHT|^3S1G_OHT|^3S1G", sample)) {

    # Assigns 3S1G-OHT samples to the H3K9 methyltransferase quadruple KO group.
    return("H3K9MT_QKO")

  } else {

    return(NA)
  }
}


# Applies the genotype-assignment function to every sample name and stores
# one genotype label for each sample.
genotype <- vapply(
  sample_names,
  get_genotype,
  character(1)
)


# Creates a sample table linking each RNA-seq sample to its genotype.
# The genotype is stored as a factor so the groups have a fixed order in DESeq2
# and in downstream plotting scripts.
sample_table <- data.frame(
  sample = sample_names,
  genotype = factor(
    genotype,
    levels = c(
      "WT",
      "HP1a_KO",
      "HP1b_KO",
      "HP1g_KO",
      "HP1ab_DKO",
      "HP1ag_DKO",
      "HP1bg_DKO",
      "HP1abg_TKO",
      "H3K9MT_QKO"
    )
  )
)


# Uses the sample names as row names so they can be matched directly
# to the expression data during the DESeq2 analysis.
rownames(sample_table) <- sample_table$sample


# Prints the sample table so the genotype assignments can be checked.
print(sample_table)


# -----------------------
# Safety checks
# -----------------------

# Stops the analysis if one or more samples could not be assigned to a genotype.
# The affected samples are printed first so naming problems can be identified.
if (any(is.na(sample_table$genotype))) {

  print(
    sample_table[
      is.na(sample_table$genotype),
      ,
      drop = FALSE
    ]
  )

  stop(
    "Some samples could not be assigned to a genotype. Check sample names."
  )
}


# Stops the analysis if no WT samples are present because WT is used as
# the reference group for all differential expression comparisons.
if (!"WT" %in% sample_table$genotype) {

  stop(
    "No WT samples found. Pairwise contrasts against WT cannot be calculated."
  )
}


# Checks specifically that any detected 3S1G-OHT samples were assigned to
# the H3K9MT_QKO group correctly.
if (any(grepl("^3S1G-OHT|^3S1G_OHT|^3S1G", sample_names)) &&
    !"H3K9MT_QKO" %in% sample_table$genotype) {

  stop(
    "3S1G-OHT samples were found but were not assigned to H3K9MT_QKO."
  )
}


# -----------------------
# Import RSEM results
# -----------------------

# Imports the gene-level RSEM results and creates matrices containing
# estimated read counts, expression abundance and gene-length information.
# These values are formatted so they can be used directly by DESeq2.
txi <- tximport(
  files,
  type = "rsem",
  txIn = FALSE,
  txOut = FALSE
)


# -----------------------
# Remove genes with invalid lengths
# -----------------------

# Identifies genes with a positive estimated length in every sample.
# Genes with zero or invalid length values cannot be handled correctly
# when the RSEM results are converted for DESeq2.
valid_genes <- rowSums(
  txi$length > 0
) == ncol(txi$length)


# Keeps only genes with valid length information in all tximport matrices.
txi$counts <- txi$counts[
  valid_genes,
]

txi$abundance <- txi$abundance[
  valid_genes,
]

txi$length <- txi$length[
  valid_genes,
]


# Prints how many genes were removed and how many remain for the analysis.
cat(
  "Removed genes with length <= 0:",
  sum(!valid_genes),
  "\n"
)

cat(
  "Remaining genes:",
  sum(valid_genes),
  "\n"
)


# -----------------------
# Create and run DESeq2 model
# -----------------------

# Creates the DESeq2 data set from the imported RSEM results.
# The design ~ genotype tells DESeq2 that differences in gene expression
# should be modeled according to the genotype of each sample.
dds <- DESeqDataSetFromTximport(
  txi = txi,
  colData = sample_table,
  design = ~ genotype
)


# Removes genes with fewer than 10 total reads across all samples.
# Very low-count genes contain little information for reliable differential
# expression testing and can add unnecessary noise to the analysis.
dds <- dds[
  rowSums(
    counts(dds)
  ) >= 10,
]


# Runs the DESeq2 model. This estimates normalization factors, gene-wise
# variability and the statistical effect of genotype on gene expression.
dds <- DESeq(dds)


# -----------------------
# Save global matrices for plotting
# -----------------------

# Saves the sample information used in the DESeq2 model.
write.csv(
  sample_table,
  file = file.path(
    out_dir,
    "DESeq2_sample_table_all_genotypes.csv"
  )
)


# Saves normalized gene counts, which correct for differences in sequencing
# depth between samples and can be used to compare expression values.
write.csv(
  counts(
    dds,
    normalized = TRUE
  ),
  file = file.path(
    out_dir,
    "DESeq2_normalized_counts_all_genotypes.csv"
  )
)


# Applies the variance-stabilizing transformation (VST) to the count data.
# VST reduces the strong dependence of variability on expression level,
# making the data more suitable for PCA, clustering and heatmaps.
# blind = FALSE keeps the genotype information from the fitted DESeq2 design
# when estimating the transformation.
vsd <- vst(
  dds,
  blind = FALSE
)


# Saves the variance-stabilized expression matrix for downstream plots.
write.csv(
  assay(vsd),
  file = file.path(
    out_dir,
    "DESeq2_vst_counts_all_genotypes.csv"
  )
)


# Saves the same main output matrices under shorter generic filenames
# so downstream plotting scripts can use stable file names.
write.csv(
  sample_table,
  file = file.path(
    out_dir,
    "DESeq2_sample_table.csv"
  )
)

write.csv(
  counts(
    dds,
    normalized = TRUE
  ),
  file = file.path(
    out_dir,
    "DESeq2_normalized_counts.csv"
  )
)

write.csv(
  assay(vsd),
  file = file.path(
    out_dir,
    "DESeq2_vst_counts.csv"
  )
)


# -----------------------
# Pairwise differential expression: each KO, including H3K9MT-QKO, vs WT
# -----------------------

# Each knockout is compared separately with WT because the biological question
# is which genes change when the respective HP1 protein combination or the
# H3K9 methyltransferases are lost. Using WT as the common reference also makes
# the expression changes across the different knockout genotypes comparable.


# Creates a list of all genotype groups except WT.
ko_genotypes <- setdiff(
  levels(sample_table$genotype),
  "WT"
)


# Keeps only knockout groups that are actually present in the current data set.
ko_genotypes <- ko_genotypes[
  ko_genotypes %in% sample_table$genotype
]


# Calculates one differential expression comparison for every knockout against WT.
for (ko in ko_genotypes) {

  cat(
    "Calculating contrast:",
    ko,
    "vs WT\n"
  )


  # Extracts the DESeq2 results for the current knockout compared with WT.
  # Positive log2 fold changes indicate higher expression in the knockout,
  # while negative values indicate lower expression in the knockout compared with WT.
  res <- results(
    dds,
    contrast = c(
      "genotype",
      ko,
      "WT"
    )
  )


  # Sorts genes by adjusted p-value so genes with the strongest statistical
  # evidence for differential expression appear first.
  res <- res[
    order(res$padj),
]


  # Defines a separate result file for the current KO-versus-WT comparison.
  out_file <- paste0(
    "DESeq2_",
    ko,
    "_vs_WT_results.csv"
  )


  # Saves the complete differential expression result table.
  write.csv(
    as.data.frame(res),
    file = file.path(
      out_dir,
      out_file
    )
  )
}


# Confirms that the DESeq2 analysis was completed and prints the output location.
cat(
  "\nDESeq2 analysis for all genotypes finished.\n"
)

cat(
  "Results saved in:",
  out_dir,
  "\n"
)