# This script visualizes the global RNA-seq expression patterns across all genotypes.
# It uses the variance-stabilized expression values generated by DESeq2 to create
# a PCA plot and a heatmap of the most variable genes.
#
# The PCA reduces the expression data to a small number of principal components
# that capture the largest differences between samples. This allows samples with
# similar overall expression profiles to cluster together and makes differences
# between WT, HP1 knockout and H3K9MT-QKO samples easier to identify.
#
# The heatmap shows the genes with the strongest expression variation across the
# complete data set. Expression values are standardized for each gene so that
# relative differences between samples can be compared independently of the
# absolute expression level of the gene.
#
# Both analyses use the same DESeq2 variance-stabilized expression matrix and are
# intended to provide an overview of sample relationships and major expression
# differences before examining individual differentially expressed genes.


# -----------------------
# Install missing packages
# -----------------------

# Defines the CRAN repository used to install general R packages.
# CRAN is the main online repository for R packages.
cran_repo <- "https://cloud.r-project.org"


# Checks whether ggplot2 is available and installs it from CRAN if needed.
if (!requireNamespace("ggplot2", quietly = TRUE)) {

  install.packages(
    "ggplot2",
    repos = cran_repo
  )
}


# Checks whether ggrepel is available and installs it from CRAN if needed.
if (!requireNamespace("ggrepel", quietly = TRUE)) {

  install.packages(
    "ggrepel",
    repos = cran_repo
  )
}


# -----------------------
# Load libraries
# -----------------------

# ggplot2 is used to create the PCA plot and heatmap.
library(ggplot2)

# ggrepel is used to place sample labels in the PCA plot while reducing
# overlap between the labels.
library(ggrepel)


# -----------------------
# Settings
# -----------------------

# Defines the main RNA-seq project folder and the input and output locations.
project_dir <- "/home1/RNAseq"

in_dir <- file.path(
  project_dir,
  "04_DESeq2_results"
)

out_dir <- file.path(
  project_dir,
  "05_analysis",
  "01_DESeq2_plots"
)


# Creates the output folder if it does not already exist.
dir.create(
  out_dir,
  showWarnings = FALSE,
  recursive = TRUE
)


# Number of genes with the highest expression variability across all samples
# used for the PCA. Selecting the most variable genes focuses the analysis on
# genes that contribute most strongly to differences between samples.
top_var_genes_pca <- 1000


# Number of genes with the highest expression variability shown in the heatmap.
top_n_heatmap <- 50


# Defines one plotting color for each genotype group.
genotype_colors <- c(
  "WT" = "#4D4D4D",
  "HP1a_KO" = "#B79AD6",
  "HP1b_KO" = "#E8899C",
  "HP1g_KO" = "#55B7B1",
  "HP1ab_DKO" = "#F2B880",
  "HP1ag_DKO" = "#8DA0CB",
  "HP1bg_DKO" = "#66C2A5",
  "HP1abg_TKO" = "#C44E52",
  "H3K9MT_QKO" = "#7EA6D9"
)


# Defines simplified genotype names used only for plot labels.
genotype_labels <- c(
  "WT" = "WT",
  "HP1a_KO" = "HP1a KO",
  "HP1b_KO" = "HP1b KO",
  "HP1g_KO" = "HP1g KO",
  "HP1ab_DKO" = "HP1ab DKO",
  "HP1ag_DKO" = "HP1ag DKO",
  "HP1bg_DKO" = "HP1bg DKO",
  "HP1abg_TKO" = "HP1abg TKO",
  "H3K9MT_QKO" = "H3K9MT QKO"
)


# Defines the colors used for low, average and high relative expression
# values in the heatmap.
heat_low <- "#55B7B1"

heat_mid <- "#F8F7F3"

heat_high <- "#E8899C"


# -----------------------
# Load DESeq2 output files
# -----------------------

# Reads the variance-stabilized expression matrix generated by DESeq2.
# Rows represent genes and columns represent RNA-seq samples.
vst_counts <- read.csv(
  file.path(
    in_dir,
    "DESeq2_vst_counts_all_genotypes.csv"
  ),
  row.names = 1,
  check.names = FALSE
)


# Reads the sample table containing the genotype assigned to each sample.
sample_table <- read.csv(
  file.path(
    in_dir,
    "DESeq2_sample_table_all_genotypes.csv"
  ),
  row.names = 1
)


# Sets a fixed genotype order so genotype groups are displayed consistently
# in the plots and legend.
sample_table$genotype <- factor(
  sample_table$genotype,
  levels = c(
    "WT",
    "HP1a_KO",
    "HP1b_KO",
    "HP1g_KO",
    "HP1ab_DKO",
    "HP1ag_DKO",
    "HP1bg_DKO",
    "HP1abg_TKO",
    "H3K9MT_QKO"
  )
)


# Identifies samples that are present in both the expression matrix and
# the sample table and keeps only these matched samples in the same order.
common_samples <- intersect(
  colnames(vst_counts),
  rownames(sample_table)
)

vst_counts <- vst_counts[
  ,
  common_samples,
  drop = FALSE
]

sample_table <- sample_table[
  common_samples,
  ,
  drop = FALSE
]


# -----------------------
# PCA plot with all genotypes
# -----------------------

# Calculates the expression variance of each gene across all samples.
gene_variance <- apply(
  vst_counts,
  1,
  var
)


# Sorts genes by their expression variance and selects the most variable genes
# for the PCA analysis.
top_pca_genes <- names(
  sort(
    gene_variance,
    decreasing = TRUE
  )
)[
  1:min(
    top_var_genes_pca,
    length(gene_variance)
  )
]


# Creates the PCA input matrix containing only the selected highly variable genes.
pca_input <- vst_counts[
  top_pca_genes,
]


# Performs principal component analysis (PCA).
# The matrix is transposed because PCA should compare samples rather than genes.
# The expression values are not scaled again because VST has already transformed
# the RNA-seq count data to make variability more comparable across genes.
pca <- prcomp(
  t(pca_input),
  scale. = FALSE
)


# Calculates the percentage of total expression variation explained by
# each principal component.
percent_var <- round(
  100 * pca$sdev^2 / sum(pca$sdev^2),
  1
)


# Creates a table containing the PC1 and PC2 coordinates of each sample
# together with its sample name and genotype.
pca_df <- data.frame(
  PC1 = pca$x[, 1],
  PC2 = pca$x[, 2],
  sample = rownames(pca$x),
  genotype = sample_table[
    rownames(pca$x),
    "genotype"
  ]
)


# Replaces underscores with spaces to make the sample names easier to read
# when they are displayed in the PCA plot.
pca_df$sample_label <- gsub(
  "_",
  " ",
  pca_df$sample
)


# Creates the PCA plot using PC1 and PC2.
# Samples are colored according to genotype and labelled individually.
# ggrepel positions the labels to reduce overlap between sample names.
p_pca <- ggplot(
  pca_df,
  aes(
    x = PC1,
    y = PC2,
    color = genotype,
    label = sample_label
  )
) +

  geom_point(
    size = 4
  ) +

  geom_text_repel(
    size = 3,
    max.overlaps = 50
  ) +

  scale_color_manual(
    values = genotype_colors,
    labels = genotype_labels,
    drop = FALSE
  ) +

  theme_minimal(
    base_size = 13
  ) +

  theme(
    plot.title = element_text(
      hjust = 0.5,
      face = "bold",
      size = 16
    ),
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) +


  # Adds the plot title and labels the PCA axes with the percentage
  # of total variation explained by PC1 and PC2.
  labs(
    title = "PCA of 1000 most variable genes",
    x = paste0(
      "PC1 (",
      percent_var[1],
      "%)"
    ),
    y = paste0(
      "PC2 (",
      percent_var[2],
      "%)"
    )
  ) +


  # Uses the same physical scale for both PCA axes so distances between
  # samples are represented consistently.
  coord_fixed()


# Saves the PCA plot as PDF and high-resolution PNG files.
ggsave(
  file.path(
    out_dir,
    "PCA_all_genotypes_top_variable_genes.pdf"
  ),
  p_pca,
  width = 8,
  height = 6
)

ggsave(
  file.path(
    out_dir,
    "PCA_all_genotypes_top_variable_genes.png"
  ),
  p_pca,
  width = 8,
  height = 6,
  dpi = 300
)


# -----------------------
# Heatmap: top variable genes across all genotypes, including H3K9MT-QKO
# -----------------------

# Selects the genes with the highest expression variance across all samples
# for visualization in the heatmap.
top_heatmap_genes <- names(
  sort(
    gene_variance,
    decreasing = TRUE
  )
)[
  1:min(
    top_n_heatmap,
    length(gene_variance)
  )
]


# Extracts the variance-stabilized expression values of the selected genes
# and converts them to a numeric matrix.
heatmap_matrix <- as.matrix(
  vst_counts[
    top_heatmap_genes,
  ]
)


# Calculates a z-score separately for each gene.
# This centers each gene around its own average expression and scales it by
# its standard deviation, allowing relative expression differences between
# samples to be compared independently of the gene's absolute expression level.
heatmap_scaled <- t(
  scale(
    t(heatmap_matrix)
  )
)


# Limits z-scores to the range -2 to 2 so extreme values do not dominate
# the heatmap color scale.
heatmap_scaled[
  heatmap_scaled > 2
] <- 2

heatmap_scaled[
  heatmap_scaled < -2
] <- -2


# Performs hierarchical clustering of genes and samples based on their
# expression patterns and determines the order shown in the heatmap.
row_order <- hclust(
  dist(
    heatmap_scaled
  )
)$order

col_order <- hclust(
  dist(
    t(heatmap_scaled)
  )
)$order


# Reorders the expression matrix according to the hierarchical clustering.
heatmap_scaled <- heatmap_scaled[
  row_order,
  col_order
]


# Converts the clustered expression matrix into a long table that can be
# used by ggplot2, with one row for every gene-sample expression value.
heatmap_df <- as.data.frame(
  as.table(
    heatmap_scaled
  )
)

colnames(heatmap_df) <- c(
  "gene",
  "sample",
  "zscore"
)


# Sets the gene order according to the hierarchical clustering.
# The order is reversed so the first clustered gene is displayed at the top.
heatmap_df$gene <- factor(
  heatmap_df$gene,
  levels = rev(
    rownames(
      heatmap_scaled
    )
  )
)


# Sets the sample order according to the hierarchical clustering.
heatmap_df$sample <- factor(
  heatmap_df$sample,
  levels = colnames(
    heatmap_scaled
  )
)


# Creates cleaner sample names for the heatmap by replacing underscores
# with spaces while keeping the original sample names for data matching.
sample_display <- gsub(
  "_",
  " ",
  colnames(
    heatmap_scaled
  )
)

names(sample_display) <- colnames(
  heatmap_scaled
)


# Creates a heatmap of relative gene expression.
# Each tile represents the z-score of one gene in one sample, with low,
# average and high relative expression represented by different colors.
p_heatmap <- ggplot(
  heatmap_df,
  aes(
    x = sample,
    y = gene,
    fill = zscore
  )
) +

  geom_tile(
    color = NA
  ) +

  scale_x_discrete(
    labels = sample_display
  ) +

  scale_fill_gradient2(
    low = heat_low,
    mid = heat_mid,
    high = heat_high,
    midpoint = 0,
    limits = c(
      -2,
      2
    ),
    name = "z-score"
  ) +

  theme_minimal(
    base_size = 12
  ) +

  theme(
    plot.title = element_text(
      hjust = 0.5,
      face = "bold",
      size = 16
    ),
    axis.title = element_blank(),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      face = "bold",
      size = 8
    ),
    axis.text.y = element_text(
      size = 6
    ),
    panel.grid = element_blank(),
    legend.title = element_text(
      face = "bold"
    ),
    legend.position = "right"
  ) +


  # Adds the plot title showing how many variable genes are included.
  labs(
    title = paste0(
      "Top ",
      length(top_heatmap_genes),
      " variable genes"
    )
  )


# Saves the heatmap as PDF and high-resolution PNG files.
ggsave(
  file.path(
    out_dir,
    "Heatmap_all_genotypes_top_variable_genes.pdf"
  ),
  p_heatmap,
  width = 10,
  height = 11
)

ggsave(
  file.path(
    out_dir,
    "Heatmap_all_genotypes_top_variable_genes.png"
  ),
  p_heatmap,
  width = 10,
  height = 11,
  dpi = 300
)


# Confirms that both plots were created and prints the output location.
cat(
  "\nPCA and variable-gene heatmap finished.\n"
)

cat(
  "Saved in:",
  out_dir,
  "\n"
)